serve:
  endpoint: /api/query
  port: 8443
  cors:
    origin: '*'
sources:
  - name: api-1
    handler:
      graphql:
        endpoint: ENDPOINT
        source: ./src/graphql/data-sauron-backoffice-api.graphql
        retry: 2
        timeout: 5000
        operationHeaders:
          Content-Type: application/json
          accept-version: '2'
  - name: api-2
    handler:
      openapi:
        baseUrl: ENDPOINT
        source: ./src/json/data-rubik-api.json
        retry: 2
        timeout: 5000
        operationHeaders:
          Content-Type: application/json
          accept-version: '2'
  - name: api-3
    handler:
      openapi:
        baseUrl: ENDPOINT
        source: ./src/json/data-shipping-backoffice-core.json
        retry: 2
        timeout: 5000
        operationHeaders:
          Content-Type: application/json
          accept-version: '2'
customFetch: ./src/utils/custom-fetch.js
transforms:
  - namingConvention:
      mode: wrap
